SET NAMES utf8mb4;
SET time_zone = '+05:30';

CREATE TABLE admins (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,profile_photo VARCHAR(255) NULL,last_login_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE students (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,phone VARCHAR(20) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,profile_photo VARCHAR(255) NULL,status ENUM('active','blocked') NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE subjects (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL UNIQUE,slug VARCHAR(120) NOT NULL UNIQUE,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE exam_catalogue (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL UNIQUE,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE topics (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,subject_id BIGINT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,UNIQUE(subject_id,name),CONSTRAINT fk_topic_subject FOREIGN KEY(subject_id) REFERENCES subjects(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE tests (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,external_id VARCHAR(100) NULL UNIQUE,unique_key CHAR(8) NOT NULL UNIQUE,title VARCHAR(220) NOT NULL,exam_name VARCHAR(120) NOT NULL DEFAULT 'General',category VARCHAR(120) NOT NULL DEFAULT 'Mock Test',thumbnail_path VARCHAR(255) NULL,subject_id BIGINT UNSIGNED NOT NULL,full_marks DECIMAL(8,2) NOT NULL,total_questions SMALLINT UNSIGNED NOT NULL,duration_minutes SMALLINT UNSIGNED NOT NULL,correct_mark DECIMAL(6,2) NOT NULL,negative_mark DECIMAL(6,2) NOT NULL DEFAULT 0,starts_at DATETIME NOT NULL,ends_at DATETIME NOT NULL,fee DECIMAL(10,2) NOT NULL DEFAULT 0,status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',created_by BIGINT UNSIGNED NOT NULL,published_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,deleted_at DATETIME NULL,INDEX idx_tests_discovery(status,starts_at,ends_at),INDEX idx_tests_catalogue(exam_name,category,subject_id),INDEX idx_tests_subject(subject_id),CONSTRAINT fk_test_subject FOREIGN KEY(subject_id) REFERENCES subjects(id),CONSTRAINT fk_test_admin FOREIGN KEY(created_by) REFERENCES admins(id),CHECK(ends_at>starts_at),CHECK(total_questions>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE questions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,unique_key CHAR(8) NOT NULL UNIQUE,test_id BIGINT UNSIGNED NOT NULL,topic_id BIGINT UNSIGNED NULL,position SMALLINT UNSIGNED NOT NULL,type ENUM('single','multiple','typed') NOT NULL,question_text TEXT NOT NULL,image_path VARCHAR(255) NULL,correct_mark DECIMAL(6,2) NOT NULL,negative_mark DECIMAL(6,2) NOT NULL DEFAULT 0,accepted_text JSON NULL,numeric_tolerance DECIMAL(12,4) NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE(test_id,position),CONSTRAINT fk_question_test FOREIGN KEY(test_id) REFERENCES tests(id),CONSTRAINT fk_question_topic FOREIGN KEY(topic_id) REFERENCES topics(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE question_options (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,question_id BIGINT UNSIGNED NOT NULL,option_key CHAR(1) NOT NULL,option_text TEXT NOT NULL,image_path VARCHAR(255) NULL,is_correct TINYINT(1) NOT NULL DEFAULT 0,UNIQUE(question_id,option_key),CONSTRAINT fk_option_question FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE cbt_import_sources (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,test_id BIGINT UNSIGNED NOT NULL,stable_key CHAR(64) NOT NULL UNIQUE,source_zip_sha256 CHAR(64) NOT NULL,source_path VARCHAR(500) NOT NULL,source_docx_sha256 CHAR(64) NOT NULL,exam_name VARCHAR(120) NOT NULL,subject_name VARCHAR(120) NOT NULL,set_number SMALLINT UNSIGNED NOT NULL,imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_cbt_import_test(test_id),CONSTRAINT fk_cbt_import_test FOREIGN KEY(test_id) REFERENCES tests(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE enrollments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,student_id BIGINT UNSIGNED NOT NULL,test_id BIGINT UNSIGNED NOT NULL,status ENUM('payment_pending','active','cancelled','refunded') NOT NULL,enrolled_at DATETIME NOT NULL,UNIQUE(student_id,test_id),INDEX idx_enrollment_test(test_id,status),CONSTRAINT fk_enroll_student FOREIGN KEY(student_id) REFERENCES students(id),CONSTRAINT fk_enroll_test FOREIGN KEY(test_id) REFERENCES tests(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,enrollment_id BIGINT UNSIGNED NOT NULL,provider VARCHAR(40) NOT NULL,provider_order_id VARCHAR(120) NOT NULL UNIQUE,provider_payment_id VARCHAR(120) NULL UNIQUE,amount DECIMAL(10,2) NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'INR',status ENUM('pending','paid','failed','refunded') NOT NULL DEFAULT 'pending',verified_at DATETIME NULL,raw_response JSON NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_payment_enrollment(enrollment_id,status),CONSTRAINT fk_payment_enrollment FOREIGN KEY(enrollment_id) REFERENCES enrollments(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE attempts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,student_id BIGINT UNSIGNED NOT NULL,test_id BIGINT UNSIGNED NOT NULL,status ENUM('in_progress','submitted','expired') NOT NULL,started_at DATETIME NOT NULL,deadline_at DATETIME NOT NULL,last_seen_at DATETIME NOT NULL,current_question_position SMALLINT UNSIGNED NOT NULL DEFAULT 1,submitted_at DATETIME NULL,obtained_marks DECIMAL(8,2) NULL,correct_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,wrong_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,skipped_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,negative_marks DECIMAL(8,2) NOT NULL DEFAULT 0,accuracy DECIMAL(6,2) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_attempt_owner(student_id,test_id,status),INDEX idx_attempt_deadline(status,deadline_at),CONSTRAINT fk_attempt_student FOREIGN KEY(student_id) REFERENCES students(id),CONSTRAINT fk_attempt_test FOREIGN KEY(test_id) REFERENCES tests(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE attempt_responses (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,attempt_id BIGINT UNSIGNED NOT NULL,question_id BIGINT UNSIGNED NOT NULL,typed_answer TEXT NULL,is_marked_review TINYINT(1) NOT NULL DEFAULT 0,is_correct TINYINT(1) NULL,mark_obtained DECIMAL(8,2) NULL,saved_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE(attempt_id,question_id),CONSTRAINT fk_response_attempt FOREIGN KEY(attempt_id) REFERENCES attempts(id) ON DELETE CASCADE,CONSTRAINT fk_response_question FOREIGN KEY(question_id) REFERENCES questions(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE response_options (response_id BIGINT UNSIGNED NOT NULL,option_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(response_id,option_id),CONSTRAINT fk_ro_response FOREIGN KEY(response_id) REFERENCES attempt_responses(id) ON DELETE CASCADE,CONSTRAINT fk_ro_option FOREIGN KEY(option_id) REFERENCES question_options(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,actor_type ENUM('admin','student','system') NOT NULL,actor_id BIGINT UNSIGNED NULL,type VARCHAR(60) NOT NULL,message VARCHAR(255) NOT NULL,context JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_audit_recent(created_at,type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE rate_limits (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,action_key CHAR(64) NOT NULL,occurred_at DATETIME NOT NULL,expires_at DATETIME NOT NULL,INDEX idx_rate_window(action_key,occurred_at),INDEX idx_rate_expiry(expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE remember_tokens (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,role ENUM('admin','student') NOT NULL,selector CHAR(24) NOT NULL UNIQUE,validator_hash CHAR(64) NOT NULL,expires_at DATETIME NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_remember_user(user_id,role),INDEX idx_remember_expiry(expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
