<section class="instruction-page student-page">
 <header class="exam-context-bar"><a class="brand student-brand exam-brand" href="/cbt/dashboard"><img src="/cbt/assets/images/logo.png" alt="Liberty logo"><span><b>LIBERTY CLASS AND CAREER</b><small>Computer Based Test</small></span></a><div class="exam-context-title"><b><?=e($test['title'])?></b><span><?=e($test['total_questions'])?> questions · <?=e($test['full_marks'])?> marks · <?=e($test['duration_minutes'])?> minutes</span></div></header>
 <main class="page narrow instruction-content"><span class="eyebrow">BEFORE YOU BEGIN</span><h1>Test instructions</h1><p>Please read everything carefully. Your timer begins only after you click “Start test”.</p>
  <div class="instruction-metrics"><article><i>◷</i><strong><?=e($test['duration_minutes'])?> minutes</strong><span>Total time</span></article><article><i>▤</i><strong><?=e($test['total_questions'])?> questions</strong><span>Total questions</span></article><article><i>★</i><strong><?=e($test['full_marks'])?> marks</strong><span>Full marks</span></article><article><i>＋</i><strong><?=e($test['correct_mark'])?> marks</strong><span>Correct answer</span></article><article><i>−</i><strong><?=e($test['negative_mark'])?> marks</strong><span>Negative marking</span></article></div>
  <section class="card instruction-rules"><h2>Important rules</h2><ol><li><i>1</i><p><b>Answer saving</b><span>Your response is saved automatically whenever you select or change an answer, and again when you use Save &amp; Next.</span></p></li><li><i>2</i><p><b>Question palette</b><span>Green means saved, purple means marked for review, amber means not attempted and an outline means not visited.</span></p></li><li><i>3</i><p><b>Final submission</b><span>You can submit at any point. Once submitted, your answers cannot be changed.</span></p></li><li><i>4</i><p><b>Time expiry</b><span>When the server timer reaches zero, your last successfully saved responses are submitted automatically.</span></p></li><li class="special"><i>Special Note</i><p><b>Connection or power interruption</b><span>If internet or power is interrupted, resume within 30 minutes and before the scheduled test end/effective deadline. After expiry no response is accepted; your last server-saved responses are final.</span></p></li></ol>
   <form method="post" action="/cbt/exam/<?=e($test['id'])?>/start"><?=csrf_field()?><label class="agree"><input type="checkbox" required> I have read and understood the instructions. I am ready to begin.</label><div class="instruction-actions"><a class="btn secondary" href="/cbt/my-tests">← Back to my tests</a><button class="btn">Start test →</button></div></form>
  </section>
 </main>
</section>
