<?php
namespace App\Controllers;
use App\Core\{Auth,Csrf,Database,HttpException,RateLimiter,Response};
use App\Services\{AttemptService,ScoringService};
final class ApiController {
 private function payload(): array {return json_decode(file_get_contents('php://input'),true)?:$_POST;}
 public function state(string $id): void {Auth::require('student');$service=new AttemptService();$a=$service->owned((int)$id,true);$service->assertOpen($a);Response::json(['ok'=>true,'server_time'=>date(DATE_ATOM),'deadline_at'=>date(DATE_ATOM,strtotime($a['deadline_at'])),'status'=>$a['status'],'current_question_position'=>(int)$a['current_question_position']]);}
 public function saveAnswer(string $id): void {Auth::require('student');Csrf::verify();RateLimiter::hit('answer-save',RateLimiter::identity().'|'.$id,180,60);$service=new AttemptService();$a=$service->owned((int)$id,true);$service->assertOpen($a);$p=$this->payload();$questionId=(int)($p['question_id']??0);$q=Database::connection()->prepare('SELECT id,type FROM questions WHERE id=? AND test_id=?');$q->execute([$questionId,$a['test_id']]);$question=$q->fetch();if(!$question)throw new HttpException(422,'Invalid question.');$optionIds=array_values(array_unique(array_filter(array_map('intval',(array)($p['option_ids']??[])))));if($question['type']==='single'&&count($optionIds)>1)throw new HttpException(422,'Select only one option.');if($question['type']==='typed'&&mb_strlen(trim((string)($p['typed_answer']??'')))>1000)throw new HttpException(422,'Typed answer is too long.');if($question['type']!=='typed'&&count($optionIds)>20)throw new HttpException(422,'Too many options selected.');$db=Database::connection();$db->beginTransaction();try{$q=$db->prepare("INSERT INTO attempt_responses(attempt_id,question_id,typed_answer,is_marked_review,saved_at,updated_at) VALUES(?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE typed_answer=VALUES(typed_answer),is_marked_review=VALUES(is_marked_review),saved_at=NOW(),updated_at=NOW()");$q->execute([(int)$id,$questionId,$question['type']==='typed'?trim((string)($p['typed_answer']??'')):null,(int)!empty($p['marked_review'])]);$s=$db->prepare('SELECT id FROM attempt_responses WHERE attempt_id=? AND question_id=?');$s->execute([(int)$id,$questionId]);$responseId=(int)$s->fetchColumn();$db->prepare('DELETE FROM response_options WHERE response_id=?')->execute([$responseId]);if($question['type']!=='typed'){foreach($optionIds as $optionId){$v=$db->prepare('SELECT id FROM question_options WHERE id=? AND question_id=?');$v->execute([$optionId,$questionId]);if(!$v->fetchColumn())throw new HttpException(422,'Invalid option.');$db->prepare('INSERT INTO response_options(response_id,option_id) VALUES(?,?)')->execute([$responseId,$optionId]);}}$db->commit();Response::json(['ok'=>true,'status'=>'saved','saved_at'=>date(DATE_ATOM)]);}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
 public function savePosition(string $id): void {Auth::require('student');Csrf::verify();$service=new AttemptService();$a=$service->owned((int)$id,true);$service->assertOpen($a);$p=$this->payload();$pos=(int)($p['position']??1);$q=Database::connection()->prepare('SELECT COUNT(*) FROM questions WHERE test_id=?');$q->execute([$a['test_id']]);$max=(int)$q->fetchColumn();if($pos<1||$pos>$max)throw new HttpException(422,'Invalid question position.');Database::connection()->prepare('UPDATE attempts SET current_question_position=?,updated_at=NOW() WHERE id=? AND student_id=?')->execute([$pos,(int)$id,Auth::id()]);Response::json(['ok'=>true]);}
 public function submit(string $id): void {Auth::require('student');Csrf::verify();RateLimiter::hit('submit',RateLimiter::identity().'|'.$id,10,300);(new AttemptService())->owned((int)$id);$result=(new ScoringService())->evaluate((int)$id);Response::json(['ok'=>true,'result'=>$result,'redirect'=>'/cbt/result/'.$id]);}
}
