<?php
namespace App\Controllers;
use App\Core\{Auth,Csrf,Database,HttpException,Response,View};
use App\Services\{AttemptService,ScoringService};
final class ExamController {
 public function instructions(string $id): void {Auth::require('student');$q=Database::connection()->prepare("SELECT t.* FROM tests t JOIN enrollments e ON e.test_id=t.id AND e.student_id=? AND e.status='active' WHERE t.id=?");$q->execute([Auth::id(),(int)$id]);$test=$q->fetch();if(!$test)throw new HttpException(403,'Enroll before opening instructions.');View::render('exam/instructions',compact('test')+['title'=>'Test Instructions']);}
 public function start(string $id): void {Auth::require('student');Csrf::verify();\App\Core\RateLimiter::hit('exam-start',\App\Core\RateLimiter::identity().'|'.$id,6,60);Response::redirect('/cbt/attempt/'.(new AttemptService())->start((int)$id));}
 public function attempt(string $id): void {Auth::require('student');$service=new AttemptService();$attempt=$service->owned((int)$id,true);$service->assertOpen($attempt);$db=Database::connection();$q=$db->prepare("SELECT q.id,q.position,q.type,q.question_text,q.image_path,q.correct_mark,q.negative_mark FROM questions q WHERE q.test_id=? ORDER BY q.position");$q->execute([$attempt['test_id']]);$questions=$q->fetchAll();foreach($questions as &$question){$o=$db->prepare('SELECT id,option_key,option_text FROM question_options WHERE question_id=? ORDER BY option_key');$o->execute([$question['id']]);$question['options']=$o->fetchAll();}$r=$db->prepare('SELECT r.*,GROUP_CONCAT(ro.option_id ORDER BY ro.option_id) selected FROM attempt_responses r LEFT JOIN response_options ro ON ro.response_id=r.id WHERE r.attempt_id=? GROUP BY r.id');$r->execute([(int)$id]);$responses=[];foreach($r->fetchAll() as $x)$responses[$x['question_id']]=$x;View::render('exam/attempt',compact('attempt','questions','responses')+['title'=>$attempt['title']]);}
 private function review(int $attemptId,int $testId): array {$db=Database::connection();$q=$db->prepare("SELECT q.*,r.typed_answer,r.is_correct,r.mark_obtained,GROUP_CONCAT(ro.option_id) selected FROM questions q LEFT JOIN attempt_responses r ON r.question_id=q.id AND r.attempt_id=? LEFT JOIN response_options ro ON ro.response_id=r.id WHERE q.test_id=? GROUP BY q.id ORDER BY q.position");$q->execute([$attemptId,$testId]);$review=$q->fetchAll();foreach($review as &$row){$o=$db->prepare('SELECT id,option_key,option_text,image_path,is_correct FROM question_options WHERE question_id=? ORDER BY option_key');$o->execute([$row['id']]);$row['options']=$o->fetchAll();}unset($row);return $review;}
 public function result(string $id): void {Auth::require('student');$attempt=(new AttemptService())->owned((int)$id);if($attempt['status']!=='submitted')throw new HttpException(409,'Submit the test before viewing results.');$review=$this->review((int)$id,(int)$attempt['test_id']);View::render('exam/result',compact('attempt','review')+['title'=>'Test Result']);}
 public function pdf(string $id): void {Auth::require('student');$attempt=(new AttemptService())->owned((int)$id);if($attempt['status']!=='submitted')throw new HttpException(409,'Result is not ready.');if(!class_exists(\Dompdf\Dompdf::class))throw new HttpException(503,'Run composer install to enable PDF export.');$review=$this->review((int)$id,(int)$attempt['test_id']);$studentName=(string)Auth::user()['name'];ob_start();View::partial('exam/result-pdf',compact('attempt','review','studentName'));$html=ob_get_clean();$pdf=new \Dompdf\Dompdf();$pdf->loadHtml($html);$pdf->setPaper('A4');$pdf->render();$pdf->stream('LCC-result-'.$id.'.pdf',['Attachment'=>true]);}
}
