<?php
namespace App\Controllers;
use App\Core\{Auth,Csrf,Database,HttpException,Response,View};
use App\Services\PaymentService;
use App\Services\UploadService;
final class StudentController {
 private function cards(string $extra='',array $params=[]): array {$sql="SELECT t.*,s.name subject,e.status enrollment_status,a.id attempt_id,a.status attempt_status,a.deadline_at,a.last_seen_at,a.current_question_position,a.obtained_marks,(SELECT COUNT(*) FROM attempt_responses ar WHERE ar.attempt_id=a.id) saved_responses FROM tests t JOIN subjects s ON s.id=t.subject_id LEFT JOIN enrollments e ON e.test_id=t.id AND e.student_id=? LEFT JOIN attempts a ON a.id=(SELECT MAX(a2.id) FROM attempts a2 WHERE a2.test_id=t.id AND a2.student_id=?) WHERE t.status='published' AND t.deleted_at IS NULL ".$extra.' ORDER BY t.starts_at LIMIT 100';$q=Database::connection()->prepare($sql);$q->execute([Auth::id(),Auth::id(),...$params]);return $q->fetchAll();}
 public function dashboard(): void
 {
  Auth::require('student');$db=Database::connection();$tests=$this->cards(' AND t.ends_at>NOW()');
  $weekStart="DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY)";
  $q=$db->prepare("SELECT t.*,s.name subject,e.status enrollment_status,a.id attempt_id,a.status attempt_status,(SELECT COUNT(*) FROM enrollments we WHERE we.test_id=t.id AND we.status='active' AND we.enrolled_at>={$weekStart}) week_enrollments FROM tests t JOIN subjects s ON s.id=t.subject_id LEFT JOIN enrollments e ON e.test_id=t.id AND e.student_id=? LEFT JOIN attempts a ON a.test_id=t.id AND a.student_id=? WHERE t.status='published' AND t.deleted_at IS NULL AND t.ends_at>NOW() ORDER BY week_enrollments DESC,t.starts_at ASC LIMIT 6");$q->execute([Auth::id(),Auth::id()]);$trending=$q->fetchAll();
  $q=$db->prepare("SELECT COUNT(*) completed,COALESCE(ROUND(AVG(CASE WHEN t.full_marks>0 THEN (a.obtained_marks/t.full_marks)*100 END),1),0) avg_score FROM attempts a JOIN tests t ON t.id=a.test_id WHERE a.student_id=? AND a.status='submitted' AND a.submitted_at>={$weekStart}");$q->execute([Auth::id()]);$week=$q->fetch()?:['completed'=>0,'avg_score'=>0];
  $subjects=[];$exams=[];foreach($tests as $test){$subjects[(string)$test['subject_id']]=$test['subject'];$exams[$test['exam_name']]=$test['exam_name'];}asort($subjects);ksort($exams);
  View::render('student/dashboard',compact('tests','trending','week','subjects','exams')+['title'=>'Student Dashboard']);
 }
 public function tests(): void {Auth::require('student');$search=trim((string)($_GET['q']??''));$subject=(int)($_GET['subject']??0);$exam=trim((string)($_GET['exam']??''));$category=trim((string)($_GET['category']??''));$extra='';$p=[];if($search!==''){$extra.=' AND (t.title LIKE ? OR t.exam_name LIKE ? OR t.category LIKE ? OR s.name LIKE ?)';$term='%'.$search.'%';array_push($p,$term,$term,$term,$term);}if($subject){$extra.=' AND t.subject_id=?';$p[]=$subject;}if($exam!==''){$extra.=' AND t.exam_name=?';$p[]=$exam;}if($category!==''){$extra.=' AND t.category=?';$p[]=$category;}$db=Database::connection();$subjects=$db->query('SELECT id,name FROM subjects ORDER BY name')->fetchAll();$exams=$db->query("SELECT DISTINCT exam_name FROM tests WHERE status='published' AND deleted_at IS NULL ORDER BY exam_name")->fetchAll(\PDO::FETCH_COLUMN);$categories=$db->query("SELECT DISTINCT category FROM tests WHERE status='published' AND deleted_at IS NULL ORDER BY category")->fetchAll(\PDO::FETCH_COLUMN);View::render('student/tests',['tests'=>$this->cards($extra,$p),'subjects'=>$subjects,'exams'=>$exams,'categories'=>$categories,'title'=>'All Tests']);}
 public function myTests(): void
 {
  Auth::require('student');$tab=(string)($_GET['tab']??'live');if(!in_array($tab,['live','upcoming','completed'],true))$tab='live';$now=time();$collections=['live'=>[],'upcoming'=>[],'completed'=>[]];
  foreach($this->cards(" AND e.status='active'") as $test){$starts=strtotime($test['starts_at']);$ends=strtotime($test['ends_at']);if(($test['attempt_status']??'')==='submitted'){$collections['completed'][]=$test;continue;}if($starts>$now){$collections['upcoming'][]=$test;continue;}$notStarted=empty($test['attempt_id']);$lastSeen=strtotime((string)$test['last_seen_at']);$pausedRemaining=strtotime((string)$test['deadline_at'])-$lastSeen;$resumable=($test['attempt_status']??'')==='in_progress'&&$lastSeen>=$now-1800&&$pausedRemaining>0&&$ends>$now;if($starts<=$now&&$ends>$now&&($notStarted||$resumable))$collections['live'][]=$test;}
  $counts=array_map('count',$collections);View::render('student/my-tests',['tests'=>$collections[$tab],'tab'=>$tab,'counts'=>$counts,'serverNow'=>date(DATE_ATOM,$now),'title'=>'My Tests']);
 }
 public function details(string $id): void {Auth::require('student');$q=Database::connection()->prepare('SELECT t.*,s.name subject FROM tests t JOIN subjects s ON s.id=t.subject_id WHERE t.id=? AND t.status=\'published\'');$q->execute([(int)$id]);$test=$q->fetch();if(!$test)throw new HttpException(404,'Test not found.');View::render('student/details',compact('test')+['title'=>$test['title']]);}
 public function enroll(string $id): void {Auth::require('student');Csrf::verify();$q=Database::connection()->prepare("SELECT * FROM tests WHERE id=? AND status='published' AND ends_at>NOW()");$q->execute([(int)$id]);$test=$q->fetch();if(!$test)throw new HttpException(404,'Test is not available.');$service=new PaymentService();$result=$service->enroll(Auth::id(),$test);$json=str_starts_with($_SERVER['REQUEST_URI']??'','/cbt/api/');if($result['status']==='payment_pending'){$payment=$service->checkout((int)$result['enrollment_id'],Auth::id());if($json)Response::json(['ok'=>true,'status'=>'payment_pending','payment'=>$this->checkoutPayload($payment)]);Response::redirect('/cbt/payment/'.$result['enrollment_id']);}if($json)Response::json(['ok'=>true,'status'=>'active','redirect'=>'/cbt/my-tests']);$_SESSION['_flash']['success']='Enrollment complete.';Response::redirect('/cbt/my-tests');}
 private function checkoutPayload(array $payment): array {return ['enrollment_id'=>(int)$payment['enrollment_id'],'checkout_key'=>(string)$payment['checkout_key'],'provider_order_id'=>(string)$payment['provider_order_id'],'amount_subunits'=>(int)$payment['amount_subunits'],'currency'=>(string)$payment['currency'],'student_name'=>(string)$payment['student_name'],'student_email'=>(string)$payment['student_email'],'student_phone'=>(string)$payment['student_phone'],'title'=>(string)$payment['title'],'verify_url'=>'/cbt/api/payments/'.(int)$payment['enrollment_id'].'/complete'];}
 public function payment(string $id): void {Auth::require('student');$payment=(new PaymentService())->checkout((int)$id,Auth::id());View::render('student/payment',compact('payment')+['title'=>'Complete Payment']);}
 public function completePayment(string $id): void {Auth::require('student');Csrf::verify();\App\Core\RateLimiter::hit('payment-verify',\App\Core\RateLimiter::identity().'|'.$id,10,300);(new PaymentService())->verify((int)$id,Auth::id(),$_POST);$_SESSION['_flash']['success']='Razorpay payment verified. Enrollment is active.';if(str_starts_with($_SERVER['REQUEST_URI']??'','/cbt/api/'))Response::json(['ok'=>true,'redirect'=>'/cbt/my-tests']);Response::redirect('/cbt/my-tests');}
 public function profilePhoto(): void {Auth::require('student');Csrf::verify();$db=Database::connection();$old=(string)(Auth::user()['profile_photo']??'');$uploadService=new UploadService();if(!empty($_POST['remove_photo'])){$db->prepare('UPDATE students SET profile_photo=NULL WHERE id=?')->execute([Auth::id()]);$_SESSION['user']['profile_photo']=null;if($old)$uploadService->delete($old);$_SESSION['_flash']['success']='Profile image removed.';Response::redirect('/cbt/dashboard');}$path=$uploadService->image($_FILES['photo']??[],'profiles');$db->prepare('UPDATE students SET profile_photo=? WHERE id=?')->execute([$path,Auth::id()]);$_SESSION['user']['profile_photo']=$path;if($old&&$old!==$path)$uploadService->delete($old);Response::redirect('/cbt/dashboard');}
}
